name: retirementplanning
favicon: null
layout_spectrum: 0.6712579031009227
typography_spectrum: 0.7451234932523221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7135298748034984
  lightness: 0.28993076318874955
  saturation: 0.852155934786424
  rhythmicContrast: 0.2777029040735215
purpose: []
